version: '3.9'
services:
  frontend:
    build: ./ghibli-animation
    container_name: ghibli-front-end
    ports:
      - 3000:3000
    working_dir: /app-frontend
    volumes:
      - ./ghibli-animation:/app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 20s
      retries: 5
  backend:
    build: ./backend
    container_name: ghibli-back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    volumes:
      - ./backend/src:/app-backend/src
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 20s
      retries: 5
    # command: dev
    env_file:
      - ./backend/.env
  db:
    image: mysql:8.0.21
    container_name: ghibli-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 5
